/* eslint-disable prettier/prettier */

export const WordsArray = [
  { word: 'tomorrow', answer: 'yesterday' },
  { word: 'problem', answer: 'solution' },
  { word: 'winner', answer: 'loser' },
  { word: 'sharp', answer: 'blunt' },
  { word: 'simple', answer: 'complex' },
  { word: 'start', answer: 'finish' },
  { word: 'forgive', answer: 'blame' },
  { word: 'friend', answer: 'enemy' },
  { word: 'create', answer: 'destroy' },
  { word: 'arrive', answer: 'depart' },
  { word: 'peace', answer: 'war' },
  { word: 'brave', answer: 'cowardly' },
  { word: 'build', answer: 'demolish' },
  { word: 'increase', answer: 'decrease' },
  { word: 'connect', answer: 'disconnect' },
  { word: 'trust', answer: 'distrust' },
  { word: 'visible', answer: 'invisible' },
  { word: 'free', answer: 'restricted' },
  { word: 'alive', answer: 'dead' },
  { word: 'growth', answer: 'decay' },
  { word: 'begin', answer: 'end' },
  { word: 'happy', answer: 'miserable' },
  { word: 'challenging', answer: 'effortless' },
  { word: 'tough', answer: 'gentle' },
  { word: 'demanding', answer: 'undemanding' },
  { word: 'intense', answer: 'mild' },
  { word: 'serious', answer: 'casual' },
  { word: 'rough', answer: 'smooth' },
  { word: 'stiff', answer: 'flexible' },
  { word: 'hectic', answer: 'calm' },
  { word: 'harsh', answer: 'gentle' },
  { word: 'fast', answer: 'slow' },
  { word: 'friendly', answer: 'hostile' },
  { word: 'warm', answer: 'cool' },
  { word: 'improve', answer: 'worsen' },
  { word: 'give', answer: 'receive' },
  { word: 'expand', answer: 'contract' },
  { word: 'accept', answer: 'reject' },
  { word: 'joy', answer: 'sorrow' },
  { word: 'beautiful', answer: 'ugly' },
];
